%YAML 1.1
---
AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS:Serverless-2016-10-31"

Parameters:
  ServiceName:
    Type: String
    Default: "aws_socialmediaapp"
    Description: The name of the ECS service to deploy the website
  AdminRole:
    Type: String
    Description: The name of the IAM role that provides administrative permissions
  DeployEnvironment:
    Type: String
    AllowedValues:
      - development
      - qualityAssurance
      - production
    Description: The deployment environment (development, quality assurance, or production)
    DomainName:
      Type: String
      Description: The custom domain name to associate with the application (e.g., myapp.com)
    HostedZoneId:
      Type: String
      Description: The Route 53 Hosted Zone ID for the given domain name
    NodeEnv:
      Type: String
      Default: production
      Description: The runtime environment for the Node.js application (e.g., production, development)
    ContainerCpu:
      Type: Number
      Default: 256
      Description: The amount of CPU (in vCPU units) allocated to the container
    ContainerMemory:
      Type: Number
      Default: 512
      Description: The memory size (in megabytes) allocated to the container
    ContainerPort:
      Type: Number
      Description: The port number exposed by the container application (e.g., 80, 3000)
    InitialTaskCount:
      Type: Number
      Description: The initial number of ECS tasks (containers) to run when the service is deployed
    MaxTaskCount:
      Type: Number
      Default: 3
      Description: The maximum number of ECS tasks allowed for autoscaling
    MinTaskCount:
      Type: Number
      Default: 1
      Description: The minimum number of ECS tasks allowed for autoscaling
    HealthCheckIntervalSeconds:
      Type: Number
      Default: 30
      Description: The interval (in seconds) between health checks performed by the load balancer on ECS tasks
    HealthCheckPath:
      Type: String
      Default: /
      Description: The path that the load balancer uses to perform health checks (e.g., `/status`)
    CPUScalingPercentage:
      Type: Number
      Default: 50
      Description: The CPU utilization percentage at which autoscaling should increase the number of ECS tasks
    RequestsPerMinuteScaling:
      Type: Number
      Default: 1000
      Description: The number of requests per minute that trigger autoscaling (above or below this value)
    PublicSubnets:
      Type: String
      Description: A comma-separated list of public subnet IDs for deploying the ECS service
    PrivateSubnets:
      Type: String
      Description: A comma-separated list of private subnet IDs for internal service components (e.g., databases)
    DefaultVPC:
      Type: String
      Description: The ID of the default VPC to use for the ECS service deployment

Conditions:
  UseCertificates:
    Fn::Equals:
      - !Ref DeployEnvironment
      - production

Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties: {}
