name: CICD Elastic Beanstalk

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch: # Allows manual trigger

env:
  PROJECT_LOCATION: .
  ELASTIC_BEANSTALK_NAME: social-media-app
  ELASTIC_BEANSTALK_ENV_NAME: Social-media-app-env

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Package application
        run: |
          zip -r ./social-media-app.zip .

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.3.3
        with:
          name: deploy-files
          path: ./social-media-app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 30

    steps:
      - uses: actions/download-artifact@v4.1.7
        with:
          name: deploy-files

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Upload to S3
        run: |
          aws s3 cp ./social-media-app.zip s3://portfolio-projects-zipped-code/social-media-app.zip

      - name: Wait for environment to be ready
        run: |
          aws elasticbeanstalk wait environment-ready \
            --application-name $ELASTIC_BEANSTALK_NAME \
            --environment-name $ELASTIC_BEANSTALK_ENV_NAME

      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name $ELASTIC_BEANSTALK_NAME \
            --version-label ${{github.run_id}} \
            --source-bundle S3Bucket="portfolio-projects-zipped-code",S3Key="social-media-app.zip"
          aws elasticbeanstalk update-environment \
            --application-name $ELASTIC_BEANSTALK_NAME \
            --environment-name $ELASTIC_BEANSTALK_ENV_NAME \
            --version-label ${{github.run_id}}
          aws elasticbeanstalk wait environment-updated \
            --application-name $ELASTIC_BEANSTALK_NAME \
            --environment-name $ELASTIC_BEANSTALK_ENV_NAME
