name: EB deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install EB CLI using pip
        run: |
          python -m pip install --upgrade pip
          pip install awsebcli

      - name: Initialize EB CLI
        run: |
          eb init -p node.js your-app-name --region ${{ secrets.AWS_REGION }}

      - name: List Environments
        run: |
          eb list

      - name: Create Environment
        run: |
          eb create your-environment-name || echo "Environment already exists or error occurred."

      - name: Use Environment
        run: |
          eb use your-environment-name

      - name: Deploy to Elastic Beanstalk
        run: |
          eb deploy
