name: Deploy to AWS

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Create ZIP deployment package
        run: zip -r deploy_package.zip ./

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create Elastic Beanstalk Application
        run: |
          aws elasticbeanstalk create-application --application-name SocialMediaApp --description "Social Media Application" || echo "Application already exists"

      - name: Create Elastic Beanstalk Environment
        run: |
          aws elasticbeanstalk create-environment \
          --application-name SocialMediaApp \
          --environment-name SocialMediaApp-env-1 \
          --solution-stack-name "64bit Amazon Linux 2 v3.4.9 running Node.js 14" || echo "Environment already exists"

      - name: Upload package to S3 bucket
        run: aws s3 cp deploy_package.zip s3://portfolio-projects-zipped-code/

      - name: Create new ElasticBeanstalk Application Version
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name SocialMediaApp \
          --source-bundle S3Bucket="portfolio-projects-zipped-code",S3Key="deploy_package.zip" \
          --version-label "ver-${{ github.sha }}" \
          --description "commit-sha-${{ github.sha }}"

      - name: Deploy new ElasticBeanstalk Application Version
        run: aws elasticbeanstalk update-environment --environment-name SocialMediaApp-env-1 --version-label "ver-${{ github.sha }}"
